apiVersion: v1
kind: Service
metadata:
  name: persistent-volumes-03
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: persistent-volumes-03

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistent-volumes-03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: persistent-volumes-03
  template:
    metadata:
      labels:
        app: persistent-volumes-03
    spec:
      volumes:
        - name: persistent-volume-claim-03
          persistentVolumeClaim:
            claimName: persistent-volume-claim-03
      containers:
        - name: persistent-volumes-03
          image: nginx:1.19
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: persistent-volume-claim-03