apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim-03
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi