apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespaces-04
#  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namespaces-04
  template:
    metadata:
      labels:
        app: namespaces-04
    spec:
      containers:
        - name: namespaces-04
          image: paulbouwer/hello-kubernetes:1.8
          ports:
            - containerPort: 8080
          env:
            - name: MESSAGE
              value: Hello Namespaces!

---

apiVersion: v1
kind: Service
metadata:
  name: namespaces-04
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: namespaces-04