apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-01
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
  selector:
    app: hello-kubernetes-01